#:schema https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json

version = 2

[[blocks]]
  type = 'prompt'
  alignment = 'left'

  [[blocks.segments]]
    type = 'session'
    style = 'plain'
    template = ' '
    background = ''
    foreground = '#58abf2'
    Text = ''
    Duration = 0
    NameLength = 0

  [[blocks.segments]]
    type = 'path'
    style = 'plain'
    template = '  {{ .Path }} '
    background = ''
    foreground = '#f1bc54'
    Text = ''
    Duration = 0
    NameLength = 0

    [blocks.segments.properties]
      folder_separator_icon = '/'
      style = 'full'

  [[blocks.segments]]
    type = 'git'
    style = 'plain'
    powerline_symbol = ''
    template = '{{ .UpstreamIcon }}{{ .HEAD }}{{ if gt .StashCount 0 }}  {{ .StashCount }}{{ end }} '
    background = ''
    foreground = '#14A5AE'
    Text = ''
    Duration = 0
    NameLength = 0

    [blocks.segments.properties]
      fetch_stash_count = true
      fetch_upstream_icon = true
  [[blocks.segments]]
    type = 'python'
    template = "{{if .Venv}}({{.Venv}}){{end}}"


[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    type = 'root'
    style = 'plain'
    template = ' '
    background = ''
    foreground = '#cd5e42'
    Text = ''
    Duration = 0
    NameLength = 0

  [[blocks.segments]]
    type = 'text'
    style = 'plain'
    template = ' '
    background = ''
    foreground = '#58abf2'
    Text = ''
    Duration = 0
    NameLength = 0


